### ISSUE TITLE
some page are not shown properly with Vimium++ enabled

### ISSUE THREAD

**Issue by gdh1995** [gdh1995/vimium-plus#11]
@taisetna Please give me a hand to list those page URLs here. For further tests, page URL, Chrome version, operating system name and version are needed. Thanks!

**Comment by taisetna** [comment]
Thank for your Interest. 
I afraid the characters of the page might not be shown properly on your browser. Because that is Korean web site page.
Anyway I write down the information what you need and attach the captured image what problem happened.

Page : http://cafe.naver.com/joonggonara
Chrome Version : 42.0.2311.152
Operaion System : Windows 10 Home

![image](https://user-images.githubusercontent.com/29498969/31487648-3ca15e28-af76-11e7-8e34-1d3f376ff4aa.png)

**Comment by gdh1995** [comment]
Confirmed, and this problem also exists on Vimium++ 1.61.2, Chrome 61 stable and Windows 10 Creator.

I'm testing and trying to fix it.

**Comment by gdh1995** [comment]
@taisetna Well, I've found and fixed a bug in `lib/extend_click.ts` (commit 14f5216a2043597a426be8a8d30b18510dad91cc).

A new version of 1.62.0 has been published on Chrome Web Store. You'll see it in a while.
Or you can try a zip version in https://github.com/gdh1995/vimium-plus/releases/tag/v1.62.0

**Comment by taisetna** [comment]
I just updated the extension now. I'll test and report the issue if something is wrong.

**Comment by gdh1995** [comment]
@taisetna Does the latest version fix the issue on all sites you have seen?

**Comment by taisetna** [comment]
The Latest Version works well till now. I'll report  If a problem occurs.

**Comment by gdh1995** [comment]
@taisetna Thanks for your help, and if there's no more pages broken, I'm closing this issue.

**Comment by taisetna** [comment]
OK. I'll open new issue If a problem occurs..
