### ISSUE TITLE
vimium ++ vs vimium

### ISSUE THREAD

**Issue by Artlant** [gdh1995/vimium-plus#12]
I would like to ask the difference between **vimium++** and **vimium** simple.
Well, you rewrote the functionality on _TypeScript_ instead of _Coffee_. The question is why? If there are any advantages, the functionality can be new or bags are fixed.
In the description there is no comparison of `vimium++ vs vimium`. Not obvious advantages.
If this fork then take you with the fix and the operating time that appear in https://github.com/philc/vimium?
Regards Raingart

**Comment by gdh1995** [comment]
Oh, Sorry. It's mainly because too many small usages have been changed to meet my personal needs, so I can not maintain a detailed change list.

Notable changes:
* Vimium++'s behaviors on LinkHints / Vomnibar modes are different in various cases - though there're no documents about new shortcuts
* some commands have new options to change their behavior - no documents yet
* `Custom search engines` has a new syntax and supports more usages
  * you may see them if you import recommended settings on Vimium++ Options page
* new commands like `searchAs` and `searchInAnother` help me to switch search engines and search new words quickly
* Vimium++ supports a custom Vomnibar page for advanced users (e.g. programmers)
* Vimium++ supports 4 Chrome global shortcuts: leftTab/rightTab/createTab/reloadTab
* Vimium++ supports the key `v` as a custom Chrome Omnibox search engine, and `v g abc <enter>` will search "abc" in Google just like what it does for Vomnibar inputs.
* Vimium++ supports new `vimium://...` urls to do some tricks
  * input `vimium://status toggle` on Vomnibar and enter to toggle current page's enabled/disabled status
  * input `vimium://parse bi https://www.google.com.hk/search?ie=utf-8&q=abc` and Vimium++ will search "abc" using bing.com.
  * input `vimium://math 1+2*3` and Vimium++ will tell the result "7"
* I'm trying my best to make Vimium++ still work well on some malformed webpages.
* it keeps supporting Chrome from ver 36 to the latest version

A few disadvantages:
* I give up supporting cross-frame LinkHints in Vimium, which shows hints on every frames of current tab
* I give up supporting `Use the link's name and characters for link-hint filtering`, because I'm a Chinese and common webpages use Chinese, so I almost never use link names.

**Comment by Artlant** [comment]
Many thanks for the detailed response.
Impressive is that:

> keeps supporting Chrome from ver 36

considering that simple Vimium` "minimum_chrome_version": "51.0"`, 

> Vimium++ supports 4 Chrome global shortcuts: leftTab/rightTab/createTab/reloadTab
but is this a feature. In the original Vimium shortcuts `[T, R, shift + >>, shift + <<]` do the same.

I did not like that there is no hotkey page when I click on the symbol `,` .This is bad.

I'm also interested. I noticed a lot of mentions and that the development is aimed at webpages use of Chinese. And what work with the sites of this language group is different from Latin-like?
What was not enough in the original _Vimium_? As far as I know that there is mainly used its "google" by name
 **Baidu**. Also  _Vimium++_ adapted to work with Arabic/Japanese/Korean_ languages?
And you laid out the project on _gihub_. But so I understand it should be blocked be **Golden Shield Project**. What should limit the majority of users in this region.

And you still have not answered you patches V++ with the original Vimium? Using their experience. Or decided to completely withdraw from them?

Simply for me at the moment there are no apparent reasons and advantages to move to V++. The fact that you switched to TS is very cool. It should greatly help avoid most bags. But at the same time you are working on a project. What if you get bored or other reasons. Its development may stop. The life of the project remains questionable.

Also, you should work on advertising to attract more users -> developers. And definitely use`Vimium++ vs Vimium` in description. Because you use the word **Vimium++** that hints at kinship and hence "the better." Perhaps it is worth to abandon this brand for example "Jackie Chan VIM" (sorry for an idiotic joke, I have a bad humor) to avoid such a stupid issue like this.

**Comment by gdh1995** [comment]
> In the original Vimium shortcuts [T, R, shift + >>, shift + <<] do the same

But Vimium's commands only work on "loaded" pages, which means you can do nothing on a broken page / Chrome Settings page. While Chrome global shortcuts work everywhere if only Chrome window is focused - this is why the 4 commands are mainly to switch or reload a tab, so that you will get a normal tab with Vimium++ enabled again.

> there is no hotkey page when I click on the symbol ,

The default shortcut to show Vimium++ help dialog (also Vimium's) is `?` (`Shift` + `/`).

> what work with the sites of this language group is different from Latin-like

Some websites use Chinese characters in their URLs. For example, a URL may be `https://www.baidu.com/s?ie=UTF-8&wd=%E7%99%BE%E5%BA%A6`, and `%E7%99%BE%E5%BA%A6` is URL-encoded `百度`. What's more, some Chinese characters may even be encoded by the GBK charset, then the encoded text is `%B0%D9%B6%C8`. Vimium++ supports them and your search text on Vomnibar will be used to match decoded texts.

And for other languages and charsets, users may set the advanced option `Locale encoding` (default to `GBK`) to make Vimium++ auto decode URLs.

> you laid out the project on github

I put this project on github so that I can access the git repo easily and everywhere. I know little about the "Golden Shield Project", but this project is not blocked/protected by anything but a MIT open-source license. There're no limits on who want to use it.

> have not answered you patches V++ with the original Vimium

Ideas of some commits to Vimium++ is from Vimium's official commits and pull requests, and sometimes I'll create pull requests for Vimium to implement wanted features / fix Vimium's known bugs. There have been a few PRs that is created by me and merged into Vimium. Other changes are for my personal needs and may cause different usages / features with Vimium.

> The life of the project remains questionable

**Yes.** But as far as I see, it's a common situation where lots of projects are trapped. One of my code principle is to make the code cost least and run fastest, so I translated Vimium's code into JavaScript code, refactor and refactor every line and use TypeScript to try to ensure correctness. So It's hard to find one totally agrees with me, and I have to keep patient.

> definitely use `Vimium++ vs Vimium` in description

I'm reworking the readme and write new documents and changelogs if I'm free enough, but a sad story is, most of my rest time has been spent in fixing found bugs and implementing new features.

> Because you use the word Vimium++ that hints at kinship and hence "the better."

It's another sad story - I was too young and too naive when I chose this name. Although now I think this name is a little shameful, I'm not ready to modify it yet, because it has been known by hundreds of users (a small number, I know). Of course, **a good new name** will be just enough to make me use it.

=================

There's another important feature I forgot to note: Vimium++ can run on other extension pages if only they declare that Vimium++ is accepted, so users may use Vimium++'s shortcuts on an extension new tab 
page. One example is my modified X New Tab (https://chrome.google.com/webstore/detail/微度新标签页修改版/hdnehngglnbnehkfcidabjckinphnief).

**Comment by Artlant** [comment]
> While Chrome global shortcuts work everywhere

Great idea. But I tried _New Tabs / chrome://settings/, drive.google.com and mail.google.com_ and it does not work exactly. Implementing in other extensions via api or calls this requires inclusion in the code. What prevents the spread. The internal isolation of the browser of important components will never allow the use of extensions everywhere - sadly but safety is paramount.


> The default shortcut to show Vimium++ help dialog (also Vimium's) is ? (Shift + /).

Oh yes, my mistake. But in Vimium ++ everything is not exactly called up a window.

> Some websites use Chinese characters in their URL

Oh. This explains a lot. I could not even think about it. But foreigners will not be able to type the URL of the site. In truth, the only symbol that I can tell is this - 大. He has the least number of sticks.

> because it has been known by hundreds of users

Perhaps there is a local analog GitHub? Given the specifics of the expansion. As far as I know, Vue.js was created in China and after the forces of the local community spread throughout the world (though its English documentation is also bad as in Vimium++ - it seems the language barrier or laziness is evident)).

> Of course, a new good name

 "**Jackie Chan VIM**" - an excellent name). Or "**The Gods Almighty Dragon Vim**" )) - I just read a few translated Chinese novels. And the pathos in their names is just off scale.


But seriously, I wish you luck in your project! Vimium++ (Vim++ or V++ does not seem to me a bad name). Saving the name of a part of users seeing in the name "++" can really associate it with _Best,Extended,Pro_ synonyms, choosing yours. Which will help spread faster. But some users (such as me) can make claims. Than so to speak it is better? It is double-edged weapon.

p.s. And in Chinese, signs are used`!` or `?` `-` that would ask a question or emphasize the importance?

**Comment by gdh1995** [comment]
> it does not work exactly

A new user need to do some configurations to get the 4 shortcuts to work. At the bottom of `chrome://extensions`, click the link `Keyboard shortcuts` and add 4 key bindings with a type of `In Chrome`. Then you'll find those bindings work well on all tabs.

Old versions of Vimium++ added default key bindings: `<a-t>` for `createTab`, `<a-c>/<a-v>` for `leftTab/rightTab` and `<a-r>` for `reloadTab`, but some users complained they failed to use these keys suddenly after installing Vimium++ (maybe they didn't notice this feature). So I've removed the default shortcut bindings.

> everything is not exactly called up a window

Sorry but I can't understand this English sentence. Vimium++'s default key mappings is from an early version of Vimium, so there may be some differences between their default mappings.

> But foreigners will not be able to type the URL of the site

This feature is mainly used to allow native speakers to search for words of their language in history URLs. because sometimes pages may have no specific titles but a common title for its whole website.

> Perhaps there is a local analog GitHub?

Maybe. I have to admit that it's enjoying to write my projects, but too so unpleasant to write documents - a common situation of most programmers.

> It is double-edged weapon

Yes. Firstly, welcome to the China culture. It's amazingly various. Secondly, I personally like the names like `VimFx` (a Firefox plugin like Chrome's Vimium) and `Vimium`, so my preferred is a word appended to `Vimium` / some characters appened to `Vim`. Anyway, it's always hard to think up a meanful and memorable name, isn't it?

> signs are used like ! or ? -

Yes. In Chinese, `!` and `?` are often used to emphasize something and in questions and imperative sentences. My knowledge about `-` is mainly from my English lessons, while the Chinese punctuation `——` has some similar meanings, and I usually use it to explain a sentence before it.
