### ISSUE TITLE
Can not use the "closeTabsOnRight"

### ISSUE THREAD

**Issue by zhidao8** [gdh1995/vimium-plus#6]
"map `<a-c>` closeTabsOnRight"
When I set this key mapping, it will become the 'previousTab'.
Chrome version 56.0.2924.87 (64-bit)
Vimium++ version 1.58

**Comment by gdh1995** [comment]
What's your key mappings?

Correct key mappings should be like:
> map Xz closeTabsOnLeft
> map Xc closeTabsOnRight

Please check:
* you have bound a key sequence to the command
* a later mapping always overrides those previous, so there should not be any other key mapping having the same key sequence
* your keyboard layout should belong to English, or some others having IMEs like Chinese, because up to now Vimium++ can not support layouts of European languages well.

Vimium++ has a recommended settings and you may click the dropdown button on the options page, which is next to "Import Settings" and at the botton-right corner, to import it. It has mapped `Xc` to `closeTabsOnRight`, so please make a try.

**Comment by zhidao8** [comment]
![1](https://cloud.githubusercontent.com/assets/23008781/23736751/187dec44-04c9-11e7-9310-aac0b2a83bdc.PNG)
![2](https://cloud.githubusercontent.com/assets/23008781/23736767/41242848-04c9-11e7-8c62-fb153fc8aaee.PNG)
Oh, sorry. I don't know why the '<a-c>' would lose, please check again.

**Comment by gdh1995** [comment]
Vimium++ has 4 suggested global keyboard shortcuts: createTab, previousTab, nextTab, reloadTab, and they're priorer than any other key mappings. By default, < a-c > is bound to previousTab, so you've met such a problem.

You can change those global shortcuts by clicking  the button at the bottom of chrome://extensions

**Comment by zhidao8** [comment]
According to what you said I have canceled suggested global keyboard shortcuts. But there is still a bug. When I press the key `Alt + c`, it just close a tab on right, not close all tabs on right.

**Comment by gdh1995** [comment]
> just a tab, not close all tabs on right

This means it works as design: closeTabsOnRight support "count" to specify how many tabs to be close. So is closeTabsOnLeft.

**Comment by gdh1995** [comment]
Is this issue solved? Or any other questions?

**Comment by zhidao8** [comment]
Yes, thanks a lot. But I think the Vimium is more convenient.

**Comment by gdh1995** [comment]
so, closed?

**Comment by zhidao8** [comment]
OK
